# Generated by Django 4.2.3 on 2023-08-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("idExercise", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                "db_table": "exercise",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("iduser", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=45, null=True)),
                ("email", models.CharField(default=None, max_length=45, null=True)),
                ("password", models.CharField(default=None, max_length=255, null=True)),
                ("role", models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("idworkout", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.IntegerField(default=None, null=True)),
                ("start_time", models.DateTimeField(default=None, null=True)),
                ("end_time", models.DateTimeField(default=None, null=True)),
                ("reps", models.IntegerField(default=None, null=True)),
                ("calories", models.IntegerField(default=None, null=True)),
                (
                    "Exercise_idExercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.user",
                    ),
                ),
            ],
            options={
                "db_table": "workout",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("idgoal", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.DateField(default=None, null=True)),
                ("end", models.DateField(default=None, null=True)),
                ("goal", models.IntegerField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.user",
                    ),
                ),
            ],
            options={
                "db_table": "goal",
            },
        ),
    ]
