<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-21 16:55

=======
# Generated by Django 4.2.4 on 2023-08-21 16:27

from django.conf import settings
>>>>>>> 4b87bfb4c01e0dcdbd6fd882ac6d0667f22ad0c9
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("idExercise", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                "db_table": "exercise",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("iduser", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=45, null=True)),
                ("email", models.CharField(default=None, max_length=45, null=True)),
                ("password", models.CharField(default=None, max_length=255, null=True)),
                ("role", models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("idworkout", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.IntegerField(default=None, null=True)),
                ("start_time", models.DateTimeField(default=None, null=True)),
                ("end_time", models.DateTimeField(default=None, null=True)),
                ("reps", models.IntegerField(default=None, null=True)),
                ("calories", models.IntegerField(default=None, null=True)),
                (
                    "Exercise_idExercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.user",
                    ),
                ),
            ],
            options={
                "db_table": "workout",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("idgoal", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.DateField(default=None, null=True)),
                ("end", models.DateField(default=None, null=True)),
                ("goal", models.IntegerField(default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AI_HealthTrainer.user",
                    ),
                ),
            ],
            options={
                "db_table": "goal",
=======
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default='null')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(verbose_name='Count')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_HealthTrainer.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Workout',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('stop', models.DateField()),
                ('goal', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal',
>>>>>>> 4b87bfb4c01e0dcdbd6fd882ac6d0667f22ad0c9
            },
        ),
    ]
