# Generated by Django 4.2.4 on 2023-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitnessdata',
            name='used_calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
