# Generated by Django 4.2.3 on 2023-08-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_HealthTrainer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="work_out_time",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
