# Generated by Django 4.2.3 on 2023-08-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AI_HealthTrainer", "0002_workout_work_out_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="work_out_time",
            new_name="workout_time",
        ),
    ]
