# Generated by Django 4.2.4 on 2023-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0002_alter_userfitnessdata_used_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
