# Generated by Django 4.2.3 on 2023-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI_HealthTrainer", "0003_rename_work_out_time_workout_workout_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="workout_time",
            field=models.FloatField(default=None, null=True),
        ),
    ]
