# Generated by Django 4.2.4 on 2023-08-21 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0003_workout_calories_workout_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
