# Generated by Django 4.2.4 on 2023-08-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0004_remove_exercise_id_exercise_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
    ]
