# Generated by Django 4.2.4 on 2023-08-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_HealthTrainer', '0005_rename_goal_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AI_HealthTrainer.goal'),
        ),
    ]
